# Generated by Django 3.1.2 on 2021-01-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
